[project]
name = "python-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=24.1.0",
    "fastapi[standard]>=0.116.1",
    "google-adk>=1.13.0",
    "manim>=0.19.0",
    "python-dotenv>=1.1.1",
]
